import { Ionicons } from "@expo/vector-icons";
import * as Location from "expo-location";
import { useState } from "react";
import { Alert, Modal, Pressable, ScrollView, Share, StyleSheet, Text, TextInput, View } from "react-native";
import Screen from "../components/Screen";
import PrimaryButton from "../components/PrimaryButton";
import { useAddress } from "../context/AddressContext";
import { colors, shadow } from "../theme";

export default function LocationScreen({ navigation }) {
  const { addresses, addAddress, selectAddress } = useAddress(); const [loading, setLoading] = useState(false); const [denied, setDenied] = useState(false); const [manualOpen, setManualOpen] = useState(false); const [manual, setManual] = useState({ label: "Home", address: "", city: "", pincode: "" });
  const goHome = () => navigation.replace("Main");
  const useCurrent = async () => { setLoading(true); setDenied(false); try { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== "granted") { setDenied(true); return; } const position = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); const results = await Location.reverseGeocodeAsync(position.coords); const place = results[0] || {}; const address = [place.name, place.street, place.district, place.city, place.region, place.postalCode].filter(Boolean).join(", "); await addAddress({ label: "Current location", address: address || "Current location", city: place.city || place.district || "", pincode: place.postalCode || "", latitude: position.coords.latitude, longitude: position.coords.longitude }); goHome(); } catch { setDenied(true); } finally { setLoading(false); } };
  const saveManual = async () => { if (manual.address.trim().length < 5 || !manual.city.trim()) return Alert.alert("Incomplete address", "Please enter your full address and city."); await addAddress(manual); setManualOpen(false); goHome(); };
  const requestFriend = () => Share.share({ message: "Please share your delivery address with me for my Smart Store order." });
  return <Screen><ScrollView contentContainerStyle={styles.content}><View style={styles.pin}><Ionicons name="location" size={38} color={colors.pink} /></View><Text style={styles.title}>Where should we deliver?</Text><Text style={styles.subtitle}>Choose a delivery location to show nearby stores and accurate delivery times.</Text>{denied ? <View style={styles.warning}><Ionicons name="information-circle" size={19} color="#A16207" /><Text style={styles.warningText}>Location permission was denied. You can still add your address manually.</Text></View> : null}<PrimaryButton title="Use my current location" onPress={useCurrent} loading={loading} /><Pressable onPress={() => setManualOpen(true)} style={styles.secondary}><Ionicons name="add-circle-outline" size={20} color={colors.purple} /><Text style={styles.secondaryText}>Add new address</Text></Pressable><Pressable onPress={requestFriend} style={styles.friend}><Ionicons name="people-outline" size={20} color={colors.muted} /><Text style={styles.friendText}>Request address from friend</Text></Pressable>{addresses.length ? <View style={styles.saved}><Text style={styles.sectionTitle}>Saved addresses</Text>{addresses.map((item) => <Pressable key={item.id} onPress={async () => { await selectAddress(item.id); goHome(); }} style={[styles.address, item.selected && styles.selected]}><View style={styles.addressIcon}><Ionicons name={item.label === "Work" ? "briefcase-outline" : "home-outline"} size={19} color={colors.purple} /></View><View style={{ flex: 1 }}><Text style={styles.addressLabel}>{item.label}</Text><Text numberOfLines={2} style={styles.addressText}>{item.address}{item.city ? `, ${item.city}` : ""}</Text></View>{item.selected ? <Ionicons name="checkmark-circle" size={22} color={colors.success} /> : null}</Pressable>)}</View> : null}</ScrollView><Modal transparent visible={manualOpen} animationType="slide" onRequestClose={() => setManualOpen(false)}><View style={styles.overlay}><View style={styles.sheet}><View style={styles.handle} /><Text style={styles.sheetTitle}>Add delivery address</Text>{[["Address label", "label"], ["Flat, house, street, landmark", "address"], ["City", "city"], ["PIN code", "pincode"]].map(([placeholder, key]) => <TextInput key={key} placeholder={placeholder} placeholderTextColor="#9E98A5" value={manual[key]} onChangeText={(value) => setManual((old) => ({ ...old, [key]: value }))} keyboardType={key === "pincode" ? "number-pad" : "default"} style={styles.input} />)}<PrimaryButton title="Save address" onPress={saveManual} /></View></View></Modal></Screen>;
}
const styles = StyleSheet.create({ content: { padding: 24, paddingBottom: 40 }, pin: { width: 76, height: 76, borderRadius: 27, backgroundColor: "#FCE7F3", alignItems: "center", justifyContent: "center", marginTop: 30, marginBottom: 22 }, title: { color: colors.ink, fontSize: 28, fontWeight: "900", letterSpacing: -.5 }, subtitle: { color: colors.muted, lineHeight: 21, marginTop: 9, marginBottom: 25 }, warning: { flexDirection: "row", gap: 9, padding: 13, backgroundColor: "#FFFBEB", borderRadius: 13, marginBottom: 16 }, warningText: { flex: 1, color: "#92400E", fontSize: 12, lineHeight: 18 }, secondary: { height: 52, borderRadius: 16, borderWidth: 1.5, borderColor: colors.purple, marginTop: 12, flexDirection: "row", gap: 8, alignItems: "center", justifyContent: "center" }, secondaryText: { color: colors.purple, fontWeight: "800" }, friend: { height: 48, flexDirection: "row", gap: 8, alignItems: "center", justifyContent: "center" }, friendText: { color: colors.muted, fontWeight: "700", fontSize: 13 }, saved: { marginTop: 22 }, sectionTitle: { color: colors.ink, fontSize: 17, fontWeight: "900", marginBottom: 12 }, address: { borderRadius: 17, padding: 14, flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "white", borderWidth: 1, borderColor: colors.border, marginBottom: 10 }, selected: { borderColor: colors.purple, backgroundColor: "#FCF9FF" }, addressIcon: { width: 40, height: 40, borderRadius: 13, backgroundColor: colors.purpleSoft, alignItems: "center", justifyContent: "center" }, addressLabel: { color: colors.ink, fontWeight: "800" }, addressText: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 3 }, overlay: { flex: 1, backgroundColor: "rgba(20,12,31,.45)", justifyContent: "flex-end" }, sheet: { backgroundColor: "white", borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 22, paddingBottom: 34, ...shadow }, handle: { width: 40, height: 4, borderRadius: 3, backgroundColor: colors.border, alignSelf: "center", marginBottom: 20 }, sheetTitle: { color: colors.ink, fontSize: 20, fontWeight: "900", marginBottom: 18 }, input: { height: 50, borderWidth: 1, borderColor: colors.border, borderRadius: 14, paddingHorizontal: 14, marginBottom: 11, color: colors.ink, backgroundColor: "#FBFAFC" } });
