import { Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import Screen from "../components/Screen";
import Field from "../components/Field";
import PrimaryButton from "../components/PrimaryButton";
import { colors } from "../theme";
import { useAuth } from "../context/AuthContext";
import { messageFromError } from "../api/client";

const emailPattern = /^\S+@\S+\.\S+$/;
export default function LoginScreen({ navigation }) {
  const { login } = useAuth();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async () => { if (!emailPattern.test(email.trim())) return setError("Please enter a valid email address."); if (!password) return setError("Password is required."); setLoading(true); setError(""); try { await login(email, password); } catch (e) { setError(e.response ? messageFromError(e, "Wrong email or password.") : e.message); } finally { setLoading(false); } };
  return <Screen style={styles.screen}><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === "ios" ? "padding" : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><View style={styles.brand}><View style={styles.logo}><Text style={{ fontSize: 29 }}>⚡</Text></View><Text style={styles.brandName}>Smart Store</Text></View><Text style={styles.title}>Welcome back</Text><Text style={styles.subtitle}>Login to get your essentials delivered fast.</Text>{error ? <View style={styles.alert}><Ionicons name="alert-circle" size={18} color={colors.danger} /><Text style={styles.alertText}>{error}</Text></View> : null}<Field label="Email address" icon="mail-outline" value={email} onChangeText={setEmail} keyboardType="email-address" autoComplete="email" placeholder="you@example.com" /><Field label="Password" icon="lock-closed-outline" value={password} onChangeText={setPassword} secureTextEntry autoComplete="current-password" placeholder="Enter your password" /><Pressable onPress={() => navigation.navigate("ForgotPassword")}><Text style={styles.forgot}>Forgot password?</Text></Pressable><PrimaryButton title="Login" loading={loading} onPress={submit} style={{ marginTop: 23 }} /><View style={styles.or}><View style={styles.line} /><Text style={styles.orText}>New to Smart Store?</Text><View style={styles.line} /></View><Pressable onPress={() => navigation.navigate("Register")} style={styles.create}><Text style={styles.createText}>Create an account</Text></Pressable></ScrollView></KeyboardAvoidingView></Screen>;
}
const styles = StyleSheet.create({ screen: { backgroundColor: "white" }, content: { flexGrow: 1, padding: 24, justifyContent: "center" }, brand: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 34 }, logo: { width: 48, height: 48, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: colors.purple }, brandName: { fontSize: 22, fontWeight: "900", color: colors.ink }, title: { fontSize: 30, fontWeight: "900", color: colors.ink, letterSpacing: -.6 }, subtitle: { color: colors.muted, lineHeight: 21, marginTop: 8, marginBottom: 25 }, alert: { flexDirection: "row", alignItems: "center", gap: 8, padding: 12, borderRadius: 12, backgroundColor: "#FFF1F2", marginBottom: 16 }, alertText: { color: colors.danger, fontSize: 12, flex: 1 }, forgot: { alignSelf: "flex-end", color: colors.purple, fontWeight: "800", fontSize: 13 }, or: { flexDirection: "row", alignItems: "center", gap: 11, marginVertical: 24 }, line: { flex: 1, height: 1, backgroundColor: colors.border }, orText: { color: colors.muted, fontSize: 12 }, create: { height: 52, borderRadius: 16, borderWidth: 1.5, borderColor: colors.purple, alignItems: "center", justifyContent: "center" }, createText: { color: colors.purple, fontWeight: "900" } });
